export const easyTopics = [
  {
    topic: "Car Brands",
    cards: [
      "Tesla",
      "Chevrolet",
      "Ford",
      "Toyota",
      "Honda",
      "BMW",
      "Volkswagen",
    ],
  },
  {
    topic: "Animals",
    cards: [
      "Lion",
      "Elephant",
      "Tiger",
      "Giraffe",
      "Penguin",
      "Shark",
      "Eagle",
      "Wolf",
      "Panda",
    ],
  },
  {
    topic: "Flowers",
    cards: ["Rose", "Tulip", "Daisy", "Lily", "Sunflower", "Orchid"],
  },
  {
    topic: "Fruits",
    cards: [
      "Apple",
      "Banana",
      "Orange",
      "Strawberry",
      "Mango",
      "Pineapple",
      "Blueberry",
      "Kiwi",
    ],
  },
  {
    topic: "Countries",
    cards: [
      "Japan",
      "Brazil",
      "Canada",
      "Australia",
      "United States",
      "France",
      "Germany",
      "Mexico",
      "Egypt",
      "Sweden",
    ],
  },
  {
    topic: "Movies",
    cards: [
      "Inception",
      "The Godfather",
      "Star Wars",
      "Jurassic Park",
      "Titanic",
      "Forrest Gump",
      "The Matrix",
      "Avengers: Endgame",
    ],
  },
  {
    topic: "Books",
    cards: [
      "To Kill a Mockingbird",
      "1984",
      "Pride and Prejudice",
      "The Great Gatsby",
      "Harry Potter and the Sorcerer's Stone",
      "The Hobbit",
      "Fahrenheit 451",
      "Animal Farm",
    ],
  },
  {
    topic: "Sports",
    cards: [
      "Soccer",
      "Basketball",
      "Tennis",
      "Swimming",
      "Golf",
      "Boxing",
      "Baseball",
      "Volleyball",
      "Rugby",
    ],
  },
  {
    topic: "Cities",
    cards: [
      "Tokyo",
      "New York",
      "Paris",
      "London",
      "Sydney",
      "Dubai",
      "Rio de Janeiro",
    ],
  },
  {
    topic: "Space",
    cards: [
      "Mars",
      "Jupiter",
      "Saturn",
      "Neptune",
      "Pluto",
      "Milky Way",
      "Black Hole",
      "Asteroid",
      "Comet",
      "Nebula",
    ],
  },
  {
    topic: "Foods",
    cards: [
      "Pizza",
      "Sushi",
      "Burger",
      "Pasta",
      "Tacos",
      "Curry",
      "Salad",
      "Ice Cream",
    ],
  },
  {
    topic: "Drinks",
    cards: [
      "Coffee",
      "Tea",
      "Lemonade",
      "Beer",
      "Wine",
      "Soda",
      "Juice",
      "Smoothie",
    ],
  },
  {
    topic: "Colors",
    cards: [
      "Red",
      "Blue",
      "Green",
      "Yellow",
      "Purple",
      "Pink",
      "Black",
      "White",
      "Brown",
    ],
  },
  {
    topic: "Shapes",
    cards: [
      "Circle",
      "Square",
      "Triangle",
      "Rectangle",
      "Oval",
      "Star",
      "Heart",
    ],
  },
  {
    topic: "Musical Instruments",
    cards: [
      "Guitar",
      "Piano",
      "Drums",
      "Violin",
      "Flute",
      "Trumpet",
      "Saxophone",
      "Harp",
    ],
  },
  {
    topic: "Weather",
    cards: [
      "Sunny",
      "Rainy",
      "Cloudy",
      "Snowy",
      "Windy",
      "Stormy",
      "Foggy",
      "Humid",
    ],
  },
  {
    topic: "Clothing",
    cards: [
      "Shirt",
      "Pants",
      "Dress",
      "Jacket",
      "Shoes",
      "Hat",
      "Socks",
      "Gloves",
      "Scarf",
    ],
  },
  {
    topic: "School Subjects",
    cards: [
      "Math",
      "Science",
      "History",
      "English",
      "Art",
      "Music",
      "Geography",
      "Physical Education",
    ],
  },
  {
    topic: "Ocean Life",
    cards: [
      "Whale",
      "Dolphin",
      "Octopus",
      "Starfish",
      "Jellyfish",
      "Seahorse",
      "Crab",
      "Turtle",
      "Coral",
    ],
  },
  {
    topic: "Kitchen Items",
    cards: [
      "Spoon",
      "Fork",
      "Knife",
      "Plate",
      "Bowl",
      "Cup",
      "Pan",
      "Oven",
      "Refrigerator",
    ],
  },
  {
    topic: "Emotions",
    cards: [
      "Happy",
      "Sad",
      "Angry",
      "Excited",
      "Nervous",
      "Calm",
      "Surprised",
      "Confused",
    ],
  },
  {
    topic: "Transportation",
    cards: [
      "Bus",
      "Train",
      "Airplane",
      "Bicycle",
      "Motorcycle",
      "Boat",
      "Subway",
      "Helicopter",
    ],
  },
  {
    topic: "Holidays",
    cards: [
      "Christmas",
      "Halloween",
      "Easter",
      "Thanksgiving",
      "New Year",
      "Valentine's Day",
      "Independence Day",
      "Birthday",
    ],
  },
  {
    topic: "Board Games",
    cards: [
      "Chess",
      "Checkers",
      "Monopoly",
      "Scrabble",
      "Risk",
      "Clue",
      "Backgammon",
      "Yahtzee",
    ],
  },
  {
    topic: "Professions",
    cards: [
      "Doctor",
      "Teacher",
      "Engineer",
      "Chef",
      "Artist",
      "Pilot",
      "Firefighter",
      "Police Officer",
      "Nurse",
    ],
  },
  {
    topic: "Furniture",
    cards: [
      "Chair",
      "Table",
      "Bed",
      "Sofa",
      "Desk",
      "Bookshelf",
      "Dresser",
      "Lamp",
    ],
  },
  {
    topic: "Technology",
    cards: [
      "Computer",
      "Smartphone",
      "Television",
      "Camera",
      "Tablet",
      "Headphones",
      "Speaker",
      "Router",
    ],
  },
  {
    topic: "Seasons",
    cards: [
      "Spring",
      "Summer",
      "Fall",
      "Winter",
      "Autumn",
      "Rainy Season",
      "Dry Season",
    ],
  },
  {
    topic: "Toys",
    cards: [
      "Doll",
      "Action Figure",
      "Puzzle",
      "Building Blocks",
      "Teddy Bear",
      "Ball",
      "Kite",
      "Yoyo",
    ],
  },
  {
    topic: "Body Parts",
    cards: [
      "Head",
      "Arms",
      "Legs",
      "Eyes",
      "Nose",
      "Mouth",
      "Ears",
      "Hands",
      "Feet",
    ],
  },
  {
    topic: "Insects",
    cards: [
      "Butterfly",
      "Bee",
      "Ant",
      "Spider",
      "Ladybug",
      "Grasshopper",
      "Dragonfly",
      "Mosquito",
    ],
  },
  {
    topic: "Vegetables",
    cards: [
      "Carrot",
      "Broccoli",
      "Spinach",
      "Tomato",
      "Potato",
      "Onion",
      "Pepper",
      "Cucumber",
      "Lettuce",
    ],
  },
  {
    topic: "Desserts",
    cards: [
      "Cake",
      "Cookie",
      "Pie",
      "Donut",
      "Candy",
      "Pudding",
      "Brownie",
      "Muffin",
    ],
  },
  {
    topic: "Tools",
    cards: [
      "Hammer",
      "Screwdriver",
      "Wrench",
      "Saw",
      "Drill",
      "Pliers",
      "Measuring Tape",
      "Level",
    ],
  },
  {
    topic: "Common Gemstones",
    cards: [
      "Diamond",
      "Ruby",
      "Emerald",
      "Sapphire",
      "Amethyst",
      "Topaz",
      "Opal",
      "Pearl",
    ],
  },
  {
    topic: "Popular Dance Styles",
    cards: [
      "Ballet",
      "Hip Hop",
      "Salsa",
      "Foxtrot",
      "Swing",
      "Tap",
      "Waltz",
      "Breakdancing",
    ],
  },
  {
    topic: "Art Supplies",
    cards: [
      "Paintbrush",
      "Canvas",
      "Pencil",
      "Crayon",
      "Marker",
      "Eraser",
      "Palette",
      "Easel",
    ],
  },
  {
    topic: "Breakfast Foods",
    cards: [
      "Cereal",
      "Toast",
      "Eggs",
      "Pancakes",
      "Waffles",
      "Oatmeal",
      "Yogurt",
      "Bacon",
    ],
  },
  {
    topic: "Card Games",
    cards: [
      "Poker",
      "Blackjack",
      "Solitaire",
      "Contract bridge",
      "Go Fish",
      "Uno",
      "Hearts",
      "Spades",
    ],
  },
  {
    topic: "Fairy Tale Characters",
    cards: [
      "Cinderella",
      "Snow White",
      "Little Red Riding Hood",
      "Goldilocks",
      "Rapunzel",
      "Sleeping Beauty",
      "Hansel and Gretel",
      "Jack the Hero",
    ],
  },
  {
    topic: "Camping Gear",
    cards: [
      "Tent",
      "Sleeping Bag",
      "Flashlight",
      "Compass",
      "Backpack",
      "Hatchet",
      "Lantern",
      "Cooler",
    ],
  },
  {
    topic: "Musical Genres",
    cards: [
      "Rock",
      "Pop",
      "Folk",
      "Classical",
      "Country",
      "Hip Hop",
      "Blues",
      "Electronic",
    ],
  },
  {
    topic: "Office Supplies",
    cards: [
      "Pen",
      "Paper",
      "Stapler",
      "Scissors",
      "Ruler",
      "Calculator",
      "Folder",
      "Paperclip",
    ],
  },
  {
    topic: "Superhero Powers",
    cards: [
      "Flying",
      "Super Strength",
      "Invisibility",
      "Telepathy",
      "Time Travel",
      "Laser Vision",
      "Teleportation",
      "Shape Shifting",
    ],
  },
  {
    topic: "Ice Cream Flavors",
    cards: [
      "Vanilla",
      "Chocolate",
      "Strawberry",
      "Mint Chip",
      "Cookie Dough",
      "Rocky Road",
      "Neapolitan",
      "Pistachio",
    ],
  },
];

export function getRandomEasyTopic() {
  const randomIndex = Math.floor(Math.random() * easyTopics.length);
  return easyTopics[randomIndex];
}
