export const hardTopics = [
  {
    topic: "Historical Figures",
    cards: [
      "Hypatia",
      "Zhang Qian",
      "Ibn Battuta",
      "Sor Juana",
      "Olaudah Equiano",
      "Ramanujan",
      "Hypatia of Alexandria",
      "Anaximander",
    ],
  },
  {
    topic: "Philosophy",
    cards: [
      "Apophasis",
      "Tautology",
      "Solipsism",
      "Panpsychism",
      "Eternalism",
      "Qualia",
      "Noumenon",
      "Anarcho-Primitivism",
      "Deconstructionism",
    ],
  },
  {
    topic: "Mathematics",
    cards: [
      "Aleph-null",
      "Zorn's Lemma",
      "Riemann Zeta",
      "Cardinality",
      "Tychonoff's Theorem",
      "P-adic Numbers",
      "Sheaf Theory",
      "Homotopy Type",
      "Grothendieck Universe",
    ],
  },
  {
    topic: "Linguistics",
    cards: [
      "Phonaestheme",
      "Clitic",
      "Epenthesis",
      "Synizesis",
      "Apophony",
      "Reduplication",
    ],
  },
  {
    topic: "Astronomy",
    cards: [
      "Quasar",
      "Magnetar",
      "Blazar",
      "Roche Lobe",
      "Lagrange Point",
      "Oort Cloud",
      "Kuiper Belt",
      "Pulsar Wind Nebula",
      "Gamma-Ray Burst",
    ],
  },
  {
    topic: "Cryptography",
    cards: [
      "Diffie-Hellman",
      "Elliptic Curve",
      "Zero-Knowledge",
      "Shamir's Secret",
      "AES-256",
      "Post-Quantum",
      "Homomorphic Encryption",
    ],
  },
  {
    topic: "Art Movements",
    cards: [
      "Dadaism",
      "Surrealism",
      "Futurism",
      "Constructivism",
      "De Stijl",
      "Fluxus",
      "Situationism",
      "Lettrism",
    ],
  },
  {
    topic: "Medical Conditions",
    cards: [
      "Progeria",
      "Fibrodysplasia",
      "Aquagenic Urticaria",
      "Alice in Wonderland Syndrome",
      "Foreign Accent",
      "Stoneman Syndrome",
      "Hyperthymesia",
      "Synesthesia",
      "Capgras Delusion",
    ],
  },
  {
    topic: "Ancient Scripts",
    cards: [
      "Cuneiform",
      "Linear A",
      "Rongorongo",
      "Ogham",
      "Brahmi",
      "Hieratic",
      "Demotic",
      "Mesoamerican Glyphs",
    ],
  },
  {
    topic: "Quantum Physics",
    cards: [
      "Renormalization",
      "Gauge Invariance",
      "Chiral Anomaly",
      "Higgs Mechanism",
      "Feynman Diagram",
      "Path Integral",
      "Wick Rotation",
      "Asymptotic Freedom",
      "Conformal Field Theory",
    ],
  },
  {
    topic: "Legal Terms",
    cards: [
      "Res Ipsa Loquitur",
      "Ergo Omnes",
      "Nemo Dat",
      "Actus Reus",
      "Mens Rea",
      "Quasi-Contract",
      "Estoppel",
    ],
  },
  {
    topic: "Exotic Plants",
    cards: [
      "Welwitschia",
      "Baobab",
      "Corpse Flower",
      "Rafflesia",
      "Venus Flytrap",
      "Pitcher Plant",
      "Ghost Orchid",
      "Jade Vine",
    ],
  },
  {
    topic: "Byzantine Emperors",
    cards: [
      "Justinian",
      "Theodora",
      "Basil II",
      "Alexios Komnenos",
      "Irene of Athens",
      "Heraclius",
      "Constantine XI",
    ],
  },
  {
    topic: "Theorists",
    cards: [
      "Derrida",
      "Foucault",
      "Lacan",
      "Deleuze",
      "Guattari",
      "Baudrillard",
      "Lyotard",
    ],
  },
  {
    topic: "Geological Eras",
    cards: [
      "Cambrian Explosion",
      "Ordovician",
      "Silurian",
      "Devonian",
      "Carboniferous",
      "Permian Extinction",
      "Triassic",
      "Jurassic",
      "Cretaceous",
    ],
  },
  {
    topic: "Neurology",
    cards: [
      "Anosognosia",
      "Prosopagnosia",
      "Aphantasia",
      "Hemispatial Neglect",
      "Alexithymia",
      "Acalculia",
      "Agraphia",
      "Apraxia",
      "Dysarthria",
    ],
  },
  {
    topic: "Extinct Languages",
    cards: [
      "Sumerian",
      "Akkadian",
      "Hittite",
      "Tocharian",
      "Gothic",
      "Etruscan",
      "Linear B",
      "Phoenician",
      "Sogdian",
    ],
  },
  {
    topic: "Particle Physics",
    cards: [
      "Muon Decay",
      "Neutrino Oscillation",
      "CP Violation",
      "Spontaneous Symmetry Breaking",
      "Quantum Chromodynamics",
      "Electroweak Unification",
      "Supersymmetry",
      "String Theory",
      "Loop Quantum Gravity",
    ],
  },
  {
    topic: "Medieval Heresies",
    cards: [
      "Catharism",
      "Arianism",
      "Donatism",
      "Pelagianism",
      "Monophysitism",
      "Nestorianism",
      "Iconoclasm",
      "Waldensians",
      "Bogomilism",
    ],
  },
  {
    topic: "Topology",
    cards: [
      "Möbius Strip",
      "Klein Bottle",
      "Torus",
      "Hyperbolic Geometry",
      "Manifold",
      "Homeomorphism",
      "Homotopy",
      "Euler Characteristic",
      "Genus",
    ],
  },
  {
    topic: "Alchemy",
    cards: [
      "Ouroboros",
      "Philosopher's Stone",
      "Azoth",
      "Antimony",
      "Vitriol",
      "Cinnabar",
      "Aqua Regia",
      "Sal Ammoniac",
      "Orpiment",
    ],
  },
  {
    topic: "Neuroscience",
    cards: [
      "Neuroplasticity",
      "Lateralization",
      "Hemispheric Dominance",
      "Executive Function",
      "Working Memory",
      "Episodic Memory",
      "Semantic Memory",
      "Procedural Memory",
      "Implicit Memory",
    ],
  },
  {
    topic: "Phobias",
    cards: [
      "Hippopotomonstrosesquippedaliophobia",
      "Silicosis",
      "Arachibutyrophobia",
      "Pogonophobia",
      "Chirophobia",
      "Ergophobia",
      "Nomophobia",
      "Trypophobia",
      "Submechanophobia",
    ],
  },
  {
    topic: "Crystals",
    cards: [
      "Triclinic",
      "Monoclinic",
      "Orthorhombic",
      "Tetragonal",
      "Trigonal",
      "Hexagonal",
      "Cubic",
      "Rhombohedral",
      "Bravais Lattice",
    ],
  },
  {
    topic: "Programming",
    cards: [
      "Brainfuck",
      "Whitespace",
      "Malbolge",
      "INTERCAL",
      "Befunge",
      "Ook!",
      "Piet",
      "Shakespeare",
      "Chef",
    ],
  },
  {
    topic: "Rare Minerals",
    cards: [
      "Painite",
      "Jeremejevite",
      "Bixbite",
      "Jadeite",
      "Taaffeite",
      "Poudretteite",
      "Musgravite",
      "Grandidierite",
      "Serendibite",
    ],
  },
  {
    topic: "Gnostic Texts",
    cards: [
      "Gospel of Thomas",
      "Gospel of Philip",
      "Apocryphon of John",
      "Pistis Sophia",
      "Gospel of Mary",
      "Thunder Perfect Mind",
      "Tripartite Tractate",
      "Hypostasis of the Archons",
      "On the Origin of the World",
    ],
  },
  {
    topic: "Rock Types",
    cards: [
      "Gneiss",
      "Schist",
      "Slate",
      "Phyllite",
      "Quartzite",
      "Marble",
      "Amphibolite",
      "Granulite",
      "Eclogite",
    ],
  },
  {
    topic: "Fallacies",
    cards: [
      "Petitio Principii",
      "Ignoratio Elenchi",
      "Argumentum ad Baculum",
      "Argumentum ad Populum",
      "Argumentum ad Verecundiam",
      "Argumentum ad Misericordiam",
      "Argumentum ad Ignorantiam",
      "Post Hoc Ergo Propter Hoc",
      "Cum Hoc Ergo Propter Hoc",
    ],
  },
  {
    topic: "Biochemistry",
    cards: [
      "Glycolysis",
      "Krebs Cycle",
      "Electron Transport Chain",
      "Calvin Cycle",
      "Pentose Phosphate",
      "Beta Oxidation",
      "Gluconeogenesis",
      "Fatty Acid Synthesis",
      "Urea Cycle",
    ],
  },
  {
    topic: "Extinct Hominids",
    cards: [
      "Australopithecus",
      "Homo Erectus",
      "Homo Habilis",
      "Homo Neanderthalensis",
      "Homo Denisova",
      "Homo Floresiensis",
      "Paranthropus",
      "Ardipithecus",
      "Sahelanthropus",
    ],
  },
  {
    topic: "Musical Modes",
    cards: [
      "Dorian",
      "Phrygian",
      "Lydian",
      "Mixolydian",
      "Aeolian",
      "Locrian",
      "Ionian",
      "Harmonic Minor",
      "Melodic Minor",
    ],
  },
  {
    topic: "Rare Earth Elements",
    cards: [
      "Neodymium",
      "Dysprosium",
      "Terbium",
      "Europium",
      "Yttrium",
      "Scandium",
      "Promethium",
      "Lutetium",
      "Thulium",
    ],
  },
  {
    topic: "Paradoxes",
    cards: [
      "Ship of Theseus",
      "Zeno's Paradox",
      "Liar Paradox",
      "Russell's Paradox",
      "Sorites Paradox",
      "Grandfather Paradox",
      "Bootstrap Paradox",
      "Fermi Paradox",
      "Olbers' Paradox",
    ],
  },
  {
    topic: "Psychology",
    cards: [
      "Cotard Delusion",
      "Fregoli Delusion",
      "Reduplicative Paramnesia",
      "Somatoparaphrenia",
      "Anosognosia",
      "Hemispatial Neglect",
      "Alien Hand Syndrome",
      "Blindsight",
      "Phantom Limb",
    ],
  },
  {
    topic: "Calculus",
    cards: [
      "Riemann Integral",
      "Lebesgue Measure",
      "Fourier Transform",
      "Laplace Transform",
      "Green's Theorem",
      "Stokes' Theorem",
      "Divergence Theorem",
      "Residue Theorem",
      "Cauchy's Theorem",
    ],
  },
  {
    topic: "Extinct Civilizations",
    cards: [
      "Harappan",
      "Minoan",
      "Mycenaean",
      "Etruscan",
      "Nubian",
      "Aksumite",
      "Tiwanaku",
      "Cahokia",
      "Anasazi",
    ],
  },
  {
    topic: "Quantum Computing",
    cards: [
      "Qubit",
      "Superposition",
      "Entanglement",
      "Decoherence",
      "Quantum Gate",
      "Bloch Sphere",
      "No-Cloning Theorem",
      "Quantum Supremacy",
      "Shor's Algorithm",
    ],
  },
  {
    topic: "Space Objects",
    cards: [
      "Brown Dwarf",
      "White Dwarf",
      "Neutron Star",
      "Magnetar",
      "Pulsar",
      "Quasar",
      "Blazar",
      "Seyfert Galaxy",
      "Herbig-Haro Object",
    ],
  },
  {
    topic: "Medieval Manuscripts",
    cards: [
      "Book of Kells",
      "Lindisfarne Gospels",
      "Codex Aureus",
      "Très Riches Heures",
      "Carmina Burana",
      "Beowulf Manuscript",
      "Domesday Book",
      "Canterbury Tales",
      "Voynich Manuscript",
    ],
  },
  {
    topic: "Thermodynamics",
    cards: [
      "Adiabatic",
      "Isothermal",
      "Isobaric",
      "Isochoric",
      "Carnot Cycle",
      "Otto Cycle",
      "Diesel Cycle",
      "Rankine Cycle",
      "Brayton Cycle",
    ],
  },
  {
    topic: "Logic Systems",
    cards: [
      "Fuzzy Logic",
      "Paraconsistent Logic",
      "Intuitionistic Logic",
      "Modal Logic",
      "Temporal Logic",
      "Deontic Logic",
      "Epistemic Logic",
      "Relevance Logic",
      "Linear Logic",
    ],
  },
  {
    topic: "Genetics",
    cards: [
      "Hutchinson-Gilford Progeria",
      "Fibrodysplasia Ossificans Progressiva",
      "Epidermolysis Bullosa",
      "Xeroderma Pigmentosum",
      "Lesch-Nyhan Syndrome",
      "Prader-Willi Syndrome",
      "Williams-Beuren Syndrome",
      "Angelman Syndrome",
      "Rett Syndrome",
    ],
  },
  {
    topic: "Architecture",
    cards: [
      "Spandrel",
      "Corbel",
      "Voussoir",
      "Impost",
      "Intrados",
      "Extrados",
      "Soffit",
      "Fascia",
      "Architrave",
    ],
  },
  {
    topic: "Religion",
    cards: [
      "Apophatic Theology",
      "Kenosis",
      "Theosis",
      "Panentheism",
      "Emanationism",
      "Docetism",
      "Antinomianism",
      "Quietism",
      "Hesychasm",
    ],
  },
];

export function getRandomHardTopic() {
  const randomIndex = Math.floor(Math.random() * hardTopics.length);
  return hardTopics[randomIndex];
}
