export const mediumTopics = [
  {
    topic: "Philosophers",
    cards: [
      "Socrates",
      "Plato",
      "Aristotle",
      "Descartes",
      "Kant",
      "Nietzsche",
      "Sartre",
      "Confucius",
      "Epicurus",
    ],
  },
  {
    topic: "Mythical Creatures",
    cards: [
      "Chimera",
      "Hydra",
      "Minotaur",
      "Phoenix",
      "Griffin",
      "Basilisk",
      "Sphinx",
    ],
  },
  {
    topic: "Chemical Elements",
    cards: [
      "Helium",
      "Neon",
      "Argon",
      "Krypton",
      "Xenon",
      "Radon",
      "Osmium",
      "Iridium",
    ],
  },
  {
    topic: "Ancient Civilizations",
    cards: [
      "Mesopotamia",
      "Indus Valley",
      "Minoan",
      "Olmec",
      "Shang Dynasty",
      "Maya",
      "Inca",
      "Aztec",
      "Hittite",
    ],
  },
  {
    topic: "Famous Composers",
    cards: [
      "Bach",
      "Beethoven",
      "Mozart",
      "Chopin",
      "Tchaikovsky",
      "Debussy",
      "Stravinsky",
    ],
  },
  {
    topic: "Literary Devices",
    cards: [
      "Metaphor",
      "Simile",
      "Alliteration",
      "Personification",
      "Hyperbole",
      "Oxymoron",
      "Anaphora",
      "Synecdoche",
      "Juxtaposition",
      "Euphemism",
    ],
  },
  {
    topic: "Planetary Moons",
    cards: [
      "Io",
      "Europa",
      "Ganymede",
      "Callisto",
      "Titan",
      "Enceladus",
      "Triton",
    ],
  },
  {
    topic: "Mathematical Theorems",
    cards: [
      "Pythagorean",
      "Fermat's Last",
      "Bayes'",
      "Central Limit",
      "Gödel's Incompleteness",
      "Euler's Formula",
    ],
  },
  {
    topic: "Obscure Capital Cities",
    cards: [
      "Ulaanbaatar",
      "Nairobi",
      "Tashkent",
      "Lilongwe",
      "Ouagadougou",
      "Yaren",
      "Funafuti",
    ],
  },
  {
    topic: "Greek Gods",
    cards: [
      "Zeus",
      "Hera",
      "Poseidon",
      "Demeter",
      "Athena",
      "Apollo",
      "Artemis",
      "Ares",
      "Hephaestus",
      "Hermes",
      "Dionysus",
    ],
  },
  {
    topic: "Physics Prize Winners",
    cards: [
      "Einstein",
      "Curie",
      "Bohr",
      "Heisenberg",
      "Feynman",
      "Higgs",
      "Kip Thorne",
    ],
  },
  {
    topic: "Endangered Species",
    cards: [
      "Amur Leopard",
      "Vaquita",
      "Javan Rhino",
      "Yangtze Finless Porpoise",
      "Saola",
      "Cross River Gorilla",
    ],
  },
  {
    topic: "Renaissance Artists",
    cards: [
      "Da Vinci",
      "Michelangelo",
      "Raphael",
      "Titian",
      "Botticelli",
      "Donatello",
    ],
  },
  {
    topic: "Quantum Physics Concepts",
    cards: [
      "Superposition",
      "Entanglement",
      "Wave-Particle Duality",
      "Uncertainty Principle",
      "Schrodinger's Cat",
      "Quantum Tunneling",
    ],
  },
  {
    topic: "World Heritage Sites",
    cards: [
      "Machu Picchu",
      "Great Wall",
      "Taj Mahal",
      "Petra",
      "Chichen Itza",
      "Colosseum",
      "Stonehenge",
      "Acropolis",
    ],
  },
  {
    topic: "Ocean Creatures",
    cards: [
      "Anglerfish",
      "Blobfish",
      "Mantis Shrimp",
      "Vampire Squid",
      "Leafy Sea Dragon",
      "Goblin Shark",
      "Giant Isopod",
      "Dumbo Octopus",
    ],
  },
  {
    topic: "Programming Languages",
    cards: [
      "Python",
      "JavaScript",
      "Rust",
      "Haskell",
      "Erlang",
      "Clojure",
      "Scala",
      "Kotlin",
      "Swift",
    ],
  },
  {
    topic: "Rare Gemstones",
    cards: [
      "Alexandrite",
      "Tanzanite",
      "Padparadscha",
      "Bixbite",
      "Jadeite",
      "Painite",
      "Jeremejevite",
      "Taaffeite",
    ],
  },
  {
    topic: "Extinct Animals",
    cards: [
      "Dodo",
      "Thylacine",
      "Quagga",
      "Passenger Pigeon",
      "Steller's Sea Cow",
      "Great Auk",
      "Baiji Dolphin",
      "Pyrenean Ibex",
    ],
  },
  {
    topic: "Architectural Styles",
    cards: [
      "Gothic",
      "Baroque",
      "Art Deco",
      "Brutalist",
      "Neoclassical",
      "Romanesque",
      "Byzantine",
      "Bauhaus",
    ],
  },
  {
    topic: "Spices and Herbs",
    cards: [
      "Cardamom",
      "Saffron",
      "Star Anise",
      "Sumac",
      "Fenugreek",
      "Asafoetida",
      "Nigella",
      "Galangal",
    ],
  },
  {
    topic: "Cloud Types",
    cards: [
      "Cirrus",
      "Cumulus",
      "Stratus",
      "Nimbus",
      "Altocumulus",
      "Cumulonimbus",
      "Mammatus",
      "Lenticular",
    ],
  },
  {
    topic: "Chess Openings",
    cards: [
      "Sicilian Defense",
      "French Defense",
      "Caro-Kann",
      "Queen's Gambit",
      "King's Indian",
      "Nimzo-Indian",
      "English Opening",
      "Ruy Lopez",
    ],
  },
  {
    topic: "Psychological Phenomena",
    cards: [
      "Confirmation Bias",
      "Dunning-Kruger",
      "Cognitive Dissonance",
      "Anchoring Effect",
      "Halo Effect",
      "Survivorship Bias",
      "Pareidolia",
      "Baader-Meinhof",
    ],
  },
  {
    topic: "Wine Regions",
    cards: [
      "Bordeaux",
      "Tuscany",
      "Napa Valley",
      "Rioja",
      "Champagne",
      "Barossa Valley",
      "Douro",
      "Marlborough",
    ],
  },
  {
    topic: "Phobias",
    cards: [
      "Arachnophobia",
      "Claustrophobia",
      "Trypophobia",
      "Megalophobia",
      "Submechanophobia",
      "Thalassophobia",
      "Nyctophobia",
      "Agoraphobia",
    ],
  },
  {
    topic: "Martial Arts",
    cards: [
      "Aikido",
      "Jujitsu",
      "Muay Thai",
      "Krav Maga",
      "Capoeira",
      "Wing Chun",
      "Systema",
      "Silat",
    ],
  },
  {
    topic: "Logical Fallacies",
    cards: [
      "Ad Hominem",
      "Straw Man",
      "False Dichotomy",
      "Slippery Slope",
      "Appeal to Authority",
      "Red Herring",
      "Circular Reasoning",
      "Bandwagon",
    ],
  },
  {
    topic: "Pasta Shapes",
    cards: [
      "Orecchiette",
      "Pappardelle",
      "Bucatini",
      "Gemelli",
      "Cavatappi",
      "Strozzapreti",
      "Radiatori",
      "Campanelle",
    ],
  },
  {
    topic: "Meteorological Terms",
    cards: [
      "Derecho",
      "Haboob",
      "Virga",
      "Graupel",
      "Supercell",
      "Mesocyclone",
      "Isobar",
      "Orographic",
    ],
  },
  {
    topic: "Art Movements",
    cards: [
      "Impressionism",
      "Abstract Expressionism",
      "Cubism",
      "Pop Art",
      "Fauvism",
      "Expressionism",
      "Pointillism",
      "Minimalism",
    ],
  },
  {
    topic: "Cocktail Ingredients",
    cards: [
      "Aperol",
      "Chartreuse",
      "Cointreau",
      "Benedictine",
      "Maraschino",
      "Cynar",
      "Amaro",
      "Lillet",
    ],
  },
  {
    topic: "Dinosaur Species",
    cards: [
      "Therizinosaurus",
      "Carnotaurus",
      "Parasaurolophus",
      "Dracorex",
      "Amargasaurus",
      "Giganotosaurus",
      "Microraptor",
      "Borealopelta",
    ],
  },
  {
    topic: "Typography Terms",
    cards: [
      "Kerning",
      "Leading",
      "Serif",
      "Ligature",
      "Baseline",
      "Ascender",
      "Descender",
      "Glyph",
    ],
  },
  {
    topic: "Fabric Types",
    cards: [
      "Jacquard",
      "Brocade",
      "Damask",
      "Organza",
      "Chiffon",
      "Tulle",
      "Gabardine",
      "Chambray",
    ],
  },
  {
    topic: "Cognitive Biases",
    cards: [
      "Availability Heuristic",
      "Recency Bias",
      "Hindsight Bias",
      "Optimism Bias",
      "Loss Aversion",
      "Framing Effect",
      "Endowment Effect",
      "Sunk Cost Fallacy",
    ],
  },
  {
    topic: "Exotic Fruits",
    cards: [
      "Durian",
      "Rambutan",
      "Jackfruit",
      "Dragon Fruit",
      "Lychee",
      "Mangosteen",
      "Cherimoya",
      "Soursop",
    ],
  },
  {
    topic: "Board Game Mechanics",
    cards: [
      "Worker Placement",
      "Deck Building",
      "Engine Building",
      "Area Control",
      "Set Collection",
      "Tile Placement",
      "Resource Management",
      "Cooperative",
    ],
  },
  {
    topic: "Encryption Methods",
    cards: [
      "AES",
      "RSA",
      "Blowfish",
      "Twofish",
      "Elliptic Curve",
      "Caesar Cipher",
      "Vigenère",
      "Enigma",
    ],
  },
  {
    topic: "Perfume Notes",
    cards: [
      "Bergamot",
      "Sandalwood",
      "Patchouli",
      "Vetiver",
      "Ylang-Ylang",
      "Frankincense",
      "Ambergris",
      "Oud",
    ],
  },
  {
    topic: "Geological Formations",
    cards: [
      "Stalactite",
      "Stalagmite",
      "Geyser",
      "Fjord",
      "Mesa",
      "Butte",
      "Escarpment",
      "Moraine",
    ],
  },
  {
    topic: "Cultural Dance Styles",
    cards: [
      "Flamenco",
      "Bharatanatyam",
      "Capoeira",
      "Butoh",
      "Krumping",
      "Voguing",
      "Lindy Hop",
      "Tango",
    ],
  },
  {
    topic: "Rhetorical Devices",
    cards: [
      "Chiasmus",
      "Antithesis",
      "Parallelism",
      "Allusion",
      "Metonymy",
      "Synesthesia",
      "Zeugma",
      "Epistrophe",
    ],
  },
  {
    topic: "Knot Types",
    cards: [
      "Bowline",
      "Clove Hitch",
      "Sheet Bend",
      "Trucker's Hitch",
      "Monkey's Fist",
      "Carrick Bend",
      "Zeppelin Bend",
      "Alpine Butterfly",
    ],
  },
  {
    topic: "Optical Illusions",
    cards: [
      "Penrose Triangle",
      "Müller-Lyer",
      "Kanizsa Triangle",
      "Ames Room",
      "Ponzo Illusion",
      "Checker Shadow",
      "Spinning Dancer",
      "Café Wall",
    ],
  },
];

export function getRandomMediumTopic() {
  const randomIndex = Math.floor(Math.random() * mediumTopics.length);
  return mediumTopics[randomIndex];
}
